name: nhs_ed_pipeline
version: '1.0.0'

profile: nhs_ed_pipeline

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

vars:
  project_id: guys-nhs

on-run-start:
  - "{{ check_source_tables_exist() }}"

on-run-end:
  - "{{ validate_row_counts() }}"

models:
  nhs_ed_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: mart
